femme(anne).
femme(betty).
femme(lisa).
femme(sylvie).
femme(eve).
femme(julie).
femme(valerie).
homme(marc).
homme(luc).
homme(jean).
homme(jules).
homme(leon).
homme(loic).
homme(gerard).
homme(jacques).
homme(herve).
homme(paul).
femme_de(anne,marc).
femme_de(betty,luc).
femme_de(lisa,jules).
femme_de(sylvie,leon).
femme_de(eve,loic).
femme_de(julie,paul).
mari_de(A,B) :-femme_de(B,A).
beaupere(B,N):-homme(B),enfant_de(X,B),enfant_de(N,X).
bellemere(B,N):-femme(B),enfant_de(X,B),enfant_de(N,X).
enfant_de(jean,marc). %	jean e copilul lui marc
enfant_de(jules,marc).
enfant_de(leon,marc).
enfant_de(jean,anne).
enfant_de(jules,anne).
enfant_de(leon,anne).
enfant_de(jacques,jules).
enfant_de(jacques,lisa).
enfant_de(herve,leon).
enfant_de(herve,sylvie).
enfant_de(julie,leon).
enfant_de(julie,sylvie).
enfant_de(lisa,luc).
enfant_de(lisa,betty).
enfant_de(loic,luc).
enfant_de(loic,betty).
enfant_de(gerard,luc).
enfant_de(gerard,betty).
enfant_de(paul,loic).
enfant_de(paul,eve).
enfant_de(valerie,loic).
enfant_de(valerie,eve).

descendent(D,A):-enfant_de(D,A).
descendent(D,A):-enfant_de(D,P),descendent(P,A).
ancetre_de(A,D):-descendent(D,A).
